---
site_name: "im-e-state-variables"
theme:
  name: material
  palette:
    scheme: default
    primary: white
    accent: blue
  features:
    - content.tabs.link
  logo: assets/logo.svg
plugins:
  - search
  - mermaid2
nav:
  # - Home: home.md
  - Index: index.md
  - Conceptual Model: about.md
markdown_extensions:
  - pymdownx.betterem
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
extra_css:
  - assets/style.css
site_url: https://Netbeheer-Nederland.github.io/im-e-state-variables
repo_url: https://github.com/Netbeheer-Nederland/im-e-state-variables
